apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
  annotations:
    webhookconverted: Webhook converted From oda.tmforum.org/v1beta3 to oda.tmforum.org/v1
spec:
  componentMetadata:
    id: {{.Values.component.id}}
    name: {{.Values.component.name}}
    version: {{.Values.component.version}}
    description: >-
      Event Management ODA-Component from Open-API reference
      implementation.
    functionalBlock: {{.Values.component.functionalBlock}}
    publicationDate: {{.Values.component.publicationDate}}
    status: specified
    maintainers:
      - name: Carlos Torres
        email: carlos.torres@ichiservice.onmicrosoft.com
    owners:
      - name: Carlos Torres
        email: carlos.torres@ichiservice.onmicrosoft.com
  coreFunction:
    exposedAPIs:
      - name: eventmanagement
        specification:
          - url: >-
              https://raw.githubusercontent.com/tmforum-apis/TMF688_EventManagement/master/TMF688-EventManagement-v4.0.0.swagger.json
        implementation: {{.Release.Name}}-eventmanagementapi
        apiType: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/eventManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/eventManagement/v4/docs
        port: {{ .Values.service.port }}
        gatewayConfiguration: {}
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction:
    exposedAPIs: []
    dependentAPIs: []
  securityFunction:
    canvasSystemRole: {{.Values.security.controllerRole}}
    exposedAPIs: []
      # - name: partyrole
      #   specification:
      #     - url: >-
      #         https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
      #   implementation: {{.Release.Name}}-partyroleapi
      #   apiType: openapi
      #   path: >-
      #     /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      #   developerUI: >-
      #     /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      #   port: 8080
      #   gatewayConfiguration: {}
    
  

